dist: trusty
sudo: false
branches:
  except:
  - /^(wip|WIP)(-|_).*$/
language: node_js
node_js:
  - "6"
before_script:
- travis_retry bundle install --without development --deployment --jobs=3 --retry=3
- travis_retry npm install
- make prepare-submodules
- make public
script: script/s3-deploy.sh
