s3_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
s3_secret: <%= ENV['S3_SECRET_KEY'] %>
s3_bucket: lab.concord.org
s3_endpoint: us-east-1
gzip:
  - .html
  - .css
  - .js
  - .svg
  - .txt
  - .json
  - .e2d

<% if ENV['TRAVIS_BRANCH'] == 'master' %>
# In this case we are going to deploy this branch to the top level of the domain
# and version/<SITE_VERSION>, so we need to ignore the old versions and branch folders.
ignore_on_server: ^(version/(?!<%= Regexp.escape(ENV['SITE_VERSION']) %>(/|\.tar\.gz))|branch/)
<% else %>
# In this case we are going to deploy this code to a subfolder of the branch folder.
# So ignore everything except this folder.
ignore_on_server: ^(?!<%= Regexp.escape(ENV['DEPLOY_DIR']) %>/)
<% end %>
max_age:
  # Default cache:
  "*": 21600 # 6 hours in seconds
  # Short cache for files often modified by authors:
  "interactives.json": 300 # 5 minutes in seconds
  "interactives/*": 300
  "models/*": 300
  "models-converted/*": 300
  "locales/*": 300
  "version/**/interactives.json": 300
  "version/**/interactives/*": 300
  "version/**/models/*": 300
  "version/**/models-converted/*": 300
  "version/**/locales/*": 300
  "version/*.tar.gz": 300
  # No cache in topic branches:
  "branch/**/*": 0
  # No cache for staging page, so devs can quickly update lab framework
  "embeddable-staging.html": 0
  # Shorter cache for production page, to reduce lab framework update delay
  "embeddable.html": 3600 # 1 hour in seconds
